# Type stub for the `atb` PyO3 extension module (compiled from sim/src/rl/pyo3.rs).
#
# The extension is a binary .so with no introspectable signatures, so IDEs and
# type checkers cannot see PyBatchEnv. This stub is the hand-maintained source of
# truth — keep it in sync with pyo3.rs when the FFI surface changes.
#
# Canonical copy lives here in the crate. A copy must also sit next to the
# installed module for the IDE to resolve it:
#     cp sim/atb.pyi rl/.venv/lib/python3.12/site-packages/atb/__init__.pyi
# (re-copy after `maturin develop` rebuilds the package).

class PyBatchEnv:
    def __init__(self, n_envs: int, config_path: str) -> None: ...
    def n_envs(self) -> int: ...

    # ── Reset ──────────────────────────────────────────────────────────────
    def reset_all(self) -> bytearray: ...
    def reset_env(self, i: int) -> bytearray: ...

    # ── Step ───────────────────────────────────────────────────────────────
    # Returns (obs_bytearray, rewards, dones); reshape obs to (n_envs, obs_total()).
    def step_batch(
        self, actions: list[int]
    ) -> tuple[bytearray, list[float], list[bool]]: ...
    def step_batch_auto_reset(
        self, actions: list[int]
    ) -> tuple[bytearray, list[float], list[bool]]: ...

    # ── MaskablePPO ────────────────────────────────────────────────────────
    # Flattened (n_envs * action_size()) row-major bool mask.
    def action_masks(self) -> list[bool]: ...

    # ── Telemetry (per-env, from the most recent step_batch) ───────────────
    # (chosen_gold_dist, is_cluster_action, own_region_had_gold, skipped_own_region)
    def decision_telemetry(
        self,
    ) -> tuple[list[int], list[bool], list[bool], list[bool]]: ...
    # Option length (sim ticks) per env — drives the SMDP γ^k discount.
    def option_ticks(self) -> list[int]: ...

    # ── Viewer state queries ───────────────────────────────────────────────
    def grid_size(self) -> tuple[int, int]: ...
    def get_tiles(self, i: int) -> list[int]: ...
    # (x, y, team, gold_carried, score)
    def get_agents(self, i: int) -> list[tuple[int, int, int, int, int]]: ...
    # (x, y, kind)
    def get_items(self, i: int) -> list[tuple[int, int, int]]: ...
    def get_tick(self, i: int) -> int: ...
    def get_match_ticks(self, i: int) -> int: ...

    # ── Layout accessors (static) ──────────────────────────────────────────
    @staticmethod
    def obs_dim() -> int: ...
    @staticmethod
    def obs_total() -> int: ...
    @staticmethod
    def obs_shape() -> tuple[int, int, int]: ...
    @staticmethod
    def mm_shape() -> tuple[int, int, int]: ...
    @staticmethod
    def cluster_features() -> int: ...
    @staticmethod
    def action_size() -> int: ...
